export interface BiblePassage {
  book: string;
  chapterNum: number;
  displayName: string;
  verses: Array<{ v: number; text: string }>;
}

export const BIBLE_LIBRARY: BiblePassage[] = [
  {
    book: 'John',
    chapterNum: 3,
    displayName: 'John 3',
    verses: [
      { v: 1,  text: 'There was a man of the Pharisees named Nicodemus, a ruler of the Jews.' },
      { v: 2,  text: 'This man came to Jesus by night and said to Him, "Rabbi, we know that You are a teacher come from God; for no one can do these signs that You do unless God is with him."' },
      { v: 3,  text: 'Jesus answered and said to him, "Most assuredly, I say to you, unless one is born again, he cannot see the kingdom of God."' },
      { v: 4,  text: 'Nicodemus said to Him, "How can a man be born when he is old? Can he enter a second time into his mother\'s womb and be born?"' },
      { v: 5,  text: 'Jesus answered, "Most assuredly, I say to you, unless one is born of water and the Spirit, he cannot enter the kingdom of God.' },
      { v: 6,  text: 'That which is born of the flesh is flesh, and that which is born of the Spirit is spirit.' },
      { v: 7,  text: 'Do not marvel that I said to you, \'You must be born again.\'' },
      { v: 8,  text: 'The wind blows where it wishes, and you hear the sound of it, but cannot tell where it comes from and where it goes. So is everyone who is born of the Spirit."' },
      { v: 9,  text: 'Nicodemus answered and said to Him, "How can these things be?"' },
      { v: 10, text: 'Jesus answered and said to him, "Are you the teacher of Israel, and do not know these things?' },
      { v: 11, text: 'Most assuredly, I say to you, We speak what We know and testify what We have seen, and you do not receive Our witness.' },
      { v: 12, text: 'If I have told you earthly things and you do not believe, how will you believe if I tell you heavenly things?' },
      { v: 13, text: 'No one has ascended to heaven but He who came down from heaven, that is, the Son of Man who is in heaven.' },
      { v: 14, text: 'And as Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,' },
      { v: 15, text: 'that whoever believes in Him should not perish but have eternal life.' },
      { v: 16, text: 'For God so loved the world that He gave His only begotten Son, that whoever believes in Him should not perish but have everlasting life.' },
      { v: 17, text: 'For God did not send His Son into the world to condemn the world, but that the world through Him might be saved.' },
      { v: 18, text: 'He who believes in Him is not condemned; but he who does not believe is condemned already, because he has not believed in the name of the only begotten Son of God.' },
      { v: 19, text: 'And this is the condemnation, that the light has come into the world, and men loved darkness rather than light, because their deeds were evil.' },
      { v: 20, text: 'For everyone practicing evil hates the light and does not come to the light, lest his deeds should be exposed.' },
      { v: 21, text: 'But he who does the truth comes to the light, that his deeds may be clearly seen, that they have been done in God."' },
      { v: 22, text: 'After these things Jesus and His disciples came into the land of Judea, and there He remained with them and baptized.' },
      { v: 23, text: 'Now John also was baptizing in Aenon near Salim, because there was much water there. And they came and were baptized.' },
      { v: 24, text: 'For John had not yet been thrown into prison.' },
      { v: 25, text: 'Then there arose a dispute between some of John\'s disciples and the Jews about purification.' },
      { v: 26, text: 'And they came to John and said to him, "Rabbi, He who was with you beyond the Jordan, to whom you have testified—behold, He is baptizing, and all are coming to Him!"' },
      { v: 27, text: 'John answered and said, "A man can receive nothing unless it has been given to him from heaven.' },
      { v: 28, text: 'You yourselves bear me witness, that I said, \'I am not the Christ,\' but, \'I have been sent before Him.\'' },
      { v: 29, text: 'He who has the bride is the bridegroom; but the friend of the bridegroom, who stands and hears him, rejoices greatly because of the bridegroom\'s voice. Therefore this joy of mine is fulfilled.' },
      { v: 30, text: 'He must increase, but I must decrease.' },
      { v: 31, text: 'He who comes from above is above all; he who is of the earth is earthly and speaks of the earth. He who comes from heaven is above all.' },
      { v: 32, text: 'And what He has seen and heard, that He testifies; and no one receives His testimony.' },
      { v: 33, text: 'He who has received His testimony has certified that God is true.' },
      { v: 34, text: 'For He whom God has sent speaks the words of God, for God does not give the Spirit by measure.' },
      { v: 35, text: 'The Father loves the Son, and has given all things into His hand.' },
      { v: 36, text: 'He who believes in the Son has everlasting life; and he who does not believe the Son shall not see life, but the wrath of God abides on him."' },
    ],
  },
  {
    book: 'John',
    chapterNum: 4,
    displayName: 'John 4',
    verses: [
      { v: 1,  text: 'Therefore, when the Lord knew that the Pharisees had heard that Jesus made and baptized more disciples than John' },
      { v: 2,  text: '(though Jesus Himself did not baptize, but His disciples),' },
      { v: 3,  text: 'He left Judea and departed again to Galilee.' },
      { v: 4,  text: 'But He needed to go through Samaria.' },
      { v: 5,  text: 'So He came to a city of Samaria which is called Sychar, near the plot of ground that Jacob gave to his son Joseph.' },
      { v: 6,  text: 'Now Jacob\'s well was there. Jesus therefore, being wearied from His journey, sat thus by the well. It was about the sixth hour.' },
      { v: 7,  text: 'A woman of Samaria came to draw water. Jesus said to her, "Give Me a drink."' },
      { v: 8,  text: 'For His disciples had gone away into the city to buy food.' },
      { v: 9,  text: 'Then the woman of Samaria said to Him, "How is it that You, being a Jew, ask a drink from me, a Samaritan woman?" For Jews have no dealings with Samaritans.' },
      { v: 10, text: 'Jesus answered and said to her, "If you knew the gift of God, and who it is who says to you, \'Give Me a drink,\' you would have asked Him, and He would have given you living water."' },
      { v: 11, text: 'The woman said to Him, "Sir, You have nothing to draw with, and the well is deep. Where then do You get that living water?' },
      { v: 12, text: 'Are You greater than our father Jacob, who gave us the well, and drank from it himself, as well as his sons and his livestock?"' },
      { v: 13, text: 'Jesus answered and said to her, "Whoever drinks of this water will thirst again,' },
      { v: 14, text: 'but whoever drinks of the water that I shall give him will never thirst. But the water that I shall give him will become in him a fountain of water springing up into everlasting life."' },
      { v: 15, text: 'The woman said to Him, "Sir, give me this water, that I may not thirst, nor come here to draw."' },
      { v: 16, text: 'Jesus said to her, "Go, call your husband, and come here."' },
      { v: 17, text: 'The woman answered and said, "I have no husband." Jesus said to her, "You have well said, \'I have no husband,\'' },
      { v: 18, text: 'for you have had five husbands, and the one whom you now have is not your husband; in that you spoke truly."' },
      { v: 19, text: 'The woman said to Him, "Sir, I perceive that You are a prophet.' },
      { v: 20, text: 'Our fathers worshiped on this mountain, and you Jews say that in Jerusalem is the place where one ought to worship."' },
      { v: 21, text: 'Jesus said to her, "Woman, believe Me, the hour is coming when you will neither on this mountain, nor in Jerusalem, worship the Father.' },
      { v: 22, text: 'You worship what you do not know; we know what we worship, for salvation is of the Jews.' },
      { v: 23, text: 'But the hour is coming, and now is, when the true worshipers will worship the Father in spirit and truth; for the Father is seeking such to worship Him.' },
      { v: 24, text: 'God is Spirit, and those who worship Him must worship in spirit and truth."' },
      { v: 25, text: 'The woman said to Him, "I know that Messiah is coming" (who is called Christ). "When He comes, He will tell us all things."' },
      { v: 26, text: 'Jesus said to her, "I who speak to you am He."' },
      { v: 27, text: 'And at this point His disciples came, and they marveled that He talked with a woman; yet no one said, "What do You seek?" or, "Why are You talking with her?"' },
      { v: 28, text: 'The woman then left her waterpot, went her way into the city, and said to the men,' },
      { v: 29, text: '"Come, see a Man who told me all things that I ever did. Could this be the Christ?"' },
      { v: 30, text: 'Then they went out of the city and came to Him.' },
      { v: 31, text: 'In the meantime His disciples urged Him, saying, "Rabbi, eat."' },
      { v: 32, text: 'But He said to them, "I have food to eat of which you do not know."' },
      { v: 33, text: 'Therefore the disciples said to one another, "Has anyone brought Him anything to eat?"' },
      { v: 34, text: 'Jesus said to them, "My food is to do the will of Him who sent Me, and to finish His work.' },
      { v: 35, text: 'Do you not say, \'There are still four months and then comes the harvest\'? Behold, I say to you, lift up your eyes and look at the fields, for they are already white for harvest!' },
      { v: 36, text: 'And he who reaps receives wages, and gathers fruit for eternal life, that both he who sows and he who reaps may rejoice together.' },
      { v: 37, text: 'For in this the saying is true: \'One sows and another reaps.\'' },
      { v: 38, text: 'I sent you to reap that for which you have not labored; others have labored, and you have entered into their labors."' },
      { v: 39, text: 'And many of the Samaritans of that city believed in Him because of the word of the woman who testified, "He told me all that I ever did."' },
      { v: 40, text: 'So when the Samaritans had come to Him, they urged Him to stay with them; and He stayed there two days.' },
      { v: 41, text: 'And many more believed because of His own word.' },
      { v: 42, text: 'Then they said to the woman, "Now we believe, not because of what you said, for we ourselves have heard Him and we know that this is indeed the Christ, the Savior of the world."' },
      { v: 43, text: 'Now after the two days He departed from there and went to Galilee.' },
      { v: 44, text: 'For Jesus Himself testified that a prophet has no honor in his own country.' },
      { v: 45, text: 'So when He came to Galilee, the Galileans received Him, having seen all the things He did in Jerusalem at the feast; for they also had gone to the feast.' },
      { v: 46, text: 'So Jesus came again to Cana of Galilee where He had made the water wine. And there was a certain nobleman whose son was sick at Capernaum.' },
      { v: 47, text: 'When he heard that Jesus had come out of Judea into Galilee, he went to Him and implored Him to come down and heal his son, for he was at the point of death.' },
      { v: 48, text: 'Then Jesus said to him, "Unless you people see signs and wonders, you will by no means believe."' },
      { v: 49, text: 'The nobleman said to Him, "Sir, come down before my child dies!"' },
      { v: 50, text: 'Jesus said to him, "Go your way; your son lives." So the man believed the word that Jesus spoke to him, and he went his way.' },
      { v: 51, text: 'And as he was now going down, his servants met him and told him, saying, "Your son lives!"' },
      { v: 52, text: 'Then he inquired of them the hour when he got better. And they said to him, "Yesterday at the seventh hour the fever left him."' },
      { v: 53, text: 'So the father knew that it was at the same hour in which Jesus said to him, "Your son lives." And he himself believed, and his whole household.' },
      { v: 54, text: 'This again is the second sign Jesus did when He had come out of Judea into Galilee.' },
    ],
  },
  {
    book: 'John',
    chapterNum: 14,
    displayName: 'John 14',
    verses: [
      { v: 1,  text: '"Let not your heart be troubled; you believe in God, believe also in Me.' },
      { v: 2,  text: 'In My Father\'s house are many mansions; if it were not so, I would have told you. I go to prepare a place for you.' },
      { v: 3,  text: 'And if I go and prepare a place for you, I will come again and receive you to Myself; that where I am, there you may be also.' },
      { v: 4,  text: 'And where I go you know, and the way you know."' },
      { v: 5,  text: 'Thomas said to Him, "Lord, we do not know where You are going, and how can we know the way?"' },
      { v: 6,  text: 'Jesus said to him, "I am the way, the truth, and the life. No one comes to the Father except through Me.' },
      { v: 7,  text: 'If you had known Me, you would have known My Father also; and from now on you know Him and have seen Him."' },
      { v: 8,  text: 'Philip said to Him, "Lord, show us the Father, and it is sufficient for us."' },
      { v: 9,  text: 'Jesus said to him, "Have I been with you so long, and yet you have not known Me, Philip? He who has seen Me has seen the Father; so how can you say, \'Show us the Father\'?' },
      { v: 10, text: 'Do you not believe that I am in the Father, and the Father in Me? The words that I speak to you I do not speak on My own authority; but the Father who dwells in Me does the works.' },
      { v: 11, text: 'Believe Me that I am in the Father and the Father in Me, or else believe Me for the sake of the works themselves.' },
      { v: 12, text: 'Most assuredly, I say to you, he who believes in Me, the works that I do he will do also; and greater works than these he will do, because I go to My Father.' },
      { v: 13, text: 'And whatever you ask in My name, that I will do, that the Father may be glorified in the Son.' },
      { v: 14, text: 'If you ask anything in My name, I will do it.' },
      { v: 15, text: 'If you love Me, keep My commandments.' },
      { v: 16, text: 'And I will pray the Father, and He will give you another Helper, that He may abide with you forever—' },
      { v: 17, text: 'the Spirit of truth, whom the world cannot receive, because it neither sees Him nor knows Him; but you know Him, for He dwells with you and will be in you.' },
      { v: 18, text: 'I will not leave you orphans; I will come to you.' },
      { v: 19, text: 'A little while longer and the world will see Me no more, but you will see Me. Because I live, you will live also.' },
      { v: 20, text: 'At that day you will know that I am in My Father, and you in Me, and I in you.' },
      { v: 21, text: 'He who has My commandments and keeps them, it is he who loves Me. And he who loves Me will be loved by My Father, and I will love him and manifest Myself to him."' },
      { v: 22, text: 'Judas (not Iscariot) said to Him, "Lord, how is it that You will manifest Yourself to us, and not to the world?"' },
      { v: 23, text: 'Jesus answered and said to him, "If anyone loves Me, he will keep My word; and My Father will love him, and We will come to him and make Our home with him.' },
      { v: 24, text: 'He who does not love Me does not keep My words; and the word which you hear is not Mine but the Father\'s who sent Me.' },
      { v: 25, text: 'These things I have spoken to you while being present with you.' },
      { v: 26, text: 'But the Helper, the Holy Spirit, whom the Father will send in My name, He will teach you all things, and bring to your remembrance all things that I said to you.' },
      { v: 27, text: 'Peace I leave with you, My peace I give to you; not as the world gives do I give to you. Let not your heart be troubled, neither let it be afraid.' },
      { v: 28, text: 'You have heard Me say to you, \'I am going away and coming back to you.\' If you loved Me, you would rejoice that I am going to the Father, for My Father is greater than I.' },
      { v: 29, text: 'And now I have told you before it comes, that when it comes to pass, you may believe.' },
      { v: 30, text: 'I will no longer talk much with you, for the ruler of this world is coming, and he has nothing in Me.' },
      { v: 31, text: 'But that the world may know that I love the Father, and as the Father gave Me commandment, so I do. Arise, let us go from here.' },
    ],
  },
  {
    book: 'John',
    chapterNum: 15,
    displayName: 'John 15',
    verses: [
      { v: 1,  text: '"I am the true vine, and My Father is the vinedresser.' },
      { v: 2,  text: 'Every branch in Me that does not bear fruit He takes away; and every branch that bears fruit He prunes, that it may bear more fruit.' },
      { v: 3,  text: 'You are already clean because of the word which I have spoken to you.' },
      { v: 4,  text: 'Abide in Me, and I in you. As the branch cannot bear fruit of itself, unless it abides in the vine, neither can you, unless you abide in Me.' },
      { v: 5,  text: 'I am the vine, you are the branches. He who abides in Me, and I in him, bears much fruit; for without Me you can do nothing.' },
      { v: 6,  text: 'If anyone does not abide in Me, he is cast out as a branch and is withered; and they gather them and throw them into the fire, and they are burned.' },
      { v: 7,  text: 'If you abide in Me, and My words abide in you, you will ask what you desire, and it shall be done for you.' },
      { v: 8,  text: 'By this My Father is glorified, that you bear much fruit; so you will be My disciples.' },
      { v: 9,  text: 'As the Father loved Me, I also have loved you; abide in My love.' },
      { v: 10, text: 'If you keep My commandments, you will abide in My love, just as I have kept My Father\'s commandments and abide in His love.' },
      { v: 11, text: 'These things I have spoken to you, that My joy may remain in you, and that your joy may be full.' },
      { v: 12, text: 'This is My commandment, that you love one another as I have loved you.' },
      { v: 13, text: 'Greater love has no one than this, than to lay down one\'s life for his friends.' },
      { v: 14, text: 'You are My friends if you do whatever I command you.' },
      { v: 15, text: 'No longer do I call you servants, for a servant does not know what his master is doing; but I have called you friends, for all things that I heard from My Father I have made known to you.' },
      { v: 16, text: 'You did not choose Me, but I chose you and appointed you that you should go and bear fruit, and that your fruit should remain, that whatever you ask the Father in My name He may give you.' },
      { v: 17, text: 'These things I command you, that you love one another.' },
      { v: 18, text: 'If the world hates you, you know that it hated Me before it hated you.' },
      { v: 19, text: 'If you were of the world, the world would love its own. Yet because you are not of the world, but I chose you out of the world, therefore the world hates you.' },
      { v: 20, text: 'Remember the word that I said to you, \'A servant is not greater than his master.\' If they persecuted Me, they will also persecute you. If they kept My word, they will keep yours also.' },
      { v: 21, text: 'But all these things they will do to you for My name\'s sake, because they do not know Him who sent Me.' },
      { v: 22, text: 'If I had not come and spoken to them, they would have no sin, but now they have no excuse for their sin.' },
      { v: 23, text: 'He who hates Me hates My Father also.' },
      { v: 24, text: 'If I had not done among them the works which no one else did, they would have no sin; but now they have seen and also hated both Me and My Father.' },
      { v: 25, text: 'But this happened that the word might be fulfilled which is written in their law, \'They hated Me without a cause.\'' },
      { v: 26, text: 'But when the Helper comes, whom I shall send to you from the Father, the Spirit of truth who proceeds from the Father, He will testify of Me.' },
      { v: 27, text: 'And you also will bear witness, because you have been with Me from the beginning.' },
    ],
  },
  {
    book: 'Psalms',
    chapterNum: 23,
    displayName: 'Psalm 23',
    verses: [
      { v: 1, text: 'The LORD is my shepherd; I shall not want.' },
      { v: 2, text: 'He makes me to lie down in green pastures; He leads me beside the still waters.' },
      { v: 3, text: 'He restores my soul; He leads me in the paths of righteousness for His name\'s sake.' },
      { v: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil; for You are with me; Your rod and Your staff, they comfort me.' },
      { v: 5, text: 'You prepare a table before me in the presence of my enemies; You anoint my head with oil; my cup runs over.' },
      { v: 6, text: 'Surely goodness and mercy shall follow me all the days of my life; and I will dwell in the house of the LORD forever.' },
    ],
  },
  {
    book: 'Romans',
    chapterNum: 8,
    displayName: 'Romans 8',
    verses: [
      { v: 1,  text: 'There is therefore now no condemnation to those who are in Christ Jesus, who do not walk according to the flesh, but according to the Spirit.' },
      { v: 2,  text: 'For the law of the Spirit of life in Christ Jesus has made me free from the law of sin and death.' },
      { v: 3,  text: 'For what the law could not do in that it was weak through the flesh, God did by sending His own Son in the likeness of sinful flesh, on account of sin: He condemned sin in the flesh,' },
      { v: 4,  text: 'that the righteous requirement of the law might be fulfilled in us who do not walk according to the flesh but according to the Spirit.' },
      { v: 5,  text: 'For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.' },
      { v: 6,  text: 'For to be carnally minded is death, but to be spiritually minded is life and peace.' },
      { v: 7,  text: 'Because the carnal mind is enmity against God; for it is not subject to the law of God, nor indeed can be.' },
      { v: 8,  text: 'So then, those who are in the flesh cannot please God.' },
      { v: 9,  text: 'But you are not in the flesh but in the Spirit, if indeed the Spirit of God dwells in you. Now if anyone does not have the Spirit of Christ, he is not His.' },
      { v: 10, text: 'And if Christ is in you, the body is dead because of sin, but the Spirit is life because of righteousness.' },
      { v: 11, text: 'But if the Spirit of Him who raised Jesus from the dead dwells in you, He who raised Christ from the dead will also give life to your mortal bodies through His Spirit who dwells in you.' },
      { v: 12, text: 'Therefore, brethren, we are debtors—not to the flesh, to live according to the flesh.' },
      { v: 13, text: 'For if you live according to the flesh you will die; but if by the Spirit you put to death the deeds of the body, you will live.' },
      { v: 14, text: 'For as many as are led by the Spirit of God, these are sons of God.' },
      { v: 15, text: 'For you did not receive the spirit of bondage again to fear, but you received the Spirit of adoption by whom we cry out, "Abba, Father."' },
      { v: 16, text: 'The Spirit Himself bears witness with our spirit that we are children of God,' },
      { v: 17, text: 'and if children, then heirs—heirs of God and joint heirs with Christ, if indeed we suffer with Him, that we may also be glorified together.' },
      { v: 18, text: 'For I consider that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.' },
      { v: 19, text: 'For the earnest expectation of the creation eagerly waits for the revealing of the sons of God.' },
      { v: 20, text: 'For the creation was subjected to futility, not willingly, but because of Him who subjected it in hope;' },
      { v: 21, text: 'because the creation itself also will be delivered from the bondage of corruption into the glorious liberty of the children of God.' },
      { v: 22, text: 'For we know that the whole creation groans and labors with birth pangs together until now.' },
      { v: 23, text: 'Not only that, but we also who have the firstfruits of the Spirit, even we ourselves groan within ourselves, eagerly waiting for the adoption, the redemption of our body.' },
      { v: 24, text: 'For we were saved in this hope, but hope that is seen is not hope; for why does one still hope for what he sees?' },
      { v: 25, text: 'But if we hope for what we do not see, we eagerly wait for it with perseverance.' },
      { v: 26, text: 'Likewise the Spirit also helps in our weaknesses. For we do not know what we should pray for as we ought, but the Spirit Himself makes intercession for us with groanings which cannot be uttered.' },
      { v: 27, text: 'Now He who searches the hearts knows what the mind of the Spirit is, because He makes intercession for the saints according to the will of God.' },
      { v: 28, text: 'And we know that all things work together for good to those who love God, to those who are the called according to His purpose.' },
      { v: 29, text: 'For whom He foreknew, He also predestined to be conformed to the image of His Son, that He might be the firstborn among many brethren.' },
      { v: 30, text: 'Moreover whom He predestined, these He also called; whom He called, these He also justified; and whom He justified, these He also glorified.' },
      { v: 31, text: 'What then shall we say to these things? If God is for us, who can be against us?' },
      { v: 32, text: 'He who did not spare His own Son, but delivered Him up for us all, how shall He not with Him also freely give us all things?' },
      { v: 33, text: 'Who shall bring a charge against God\'s elect? It is God who justifies.' },
      { v: 34, text: 'Who is he who condemns? It is Christ who died, and furthermore is also risen, who is even at the right hand of God, who also makes intercession for us.' },
      { v: 35, text: 'Who shall separate us from the love of Christ? Shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?' },
      { v: 36, text: 'As it is written: "For Your sake we are killed all day long; we are accounted as sheep for the slaughter."' },
      { v: 37, text: 'Yet in all these things we are more than conquerors through Him who loved us.' },
      { v: 38, text: 'For I am persuaded that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come,' },
      { v: 39, text: 'nor height nor depth, nor any other created thing, shall be able to separate us from the love of God which is in Christ Jesus our Lord.' },
    ],
  },
  {
    book: 'Philippians',
    chapterNum: 4,
    displayName: 'Philippians 4',
    verses: [
      { v: 1,  text: 'Therefore, my beloved and longed-for brethren, my joy and crown, so stand fast in the Lord, beloved.' },
      { v: 2,  text: 'I implore Euodia and I implore Syntyche to be of the same mind in the Lord.' },
      { v: 3,  text: 'And I urge you also, true companion, help these women who labored with me in the gospel, with Clement also, and the rest of my fellow workers, whose names are in the Book of Life.' },
      { v: 4,  text: 'Rejoice in the Lord always. Again I will say, rejoice!' },
      { v: 5,  text: 'Let your gentleness be known to all men. The Lord is at hand.' },
      { v: 6,  text: 'Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God;' },
      { v: 7,  text: 'and the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus.' },
      { v: 8,  text: 'Finally, brethren, whatever things are true, whatever things are noble, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report, if there is any virtue and if there is anything praiseworthy—meditate on these things.' },
      { v: 9,  text: 'The things which you learned and received and heard and saw in me, these do, and the God of peace will be with you.' },
      { v: 10, text: 'But I rejoiced in the Lord greatly that now at last your care for me has flourished again; though you surely did care, but you lacked opportunity.' },
      { v: 11, text: 'Not that I speak in regard to need, for I have learned, in whatever state I am, to be content:' },
      { v: 12, text: 'I know how to be abased, and I know how to abound. Everywhere and in all things I have learned both to be full and to be hungry, both to abound and to suffer need.' },
      { v: 13, text: 'I can do all things through Christ who strengthens me.' },
      { v: 14, text: 'Nevertheless you have done well that you shared in my distress.' },
      { v: 15, text: 'Now you Philippians know also that in the beginning of the gospel, when I departed from Macedonia, no church shared with me concerning giving and receiving but you only.' },
      { v: 16, text: 'For even in Thessalonica you sent aid once and again for my necessities.' },
      { v: 17, text: 'Not that I desire a gift, but I desire fruit that abounds to your account.' },
      { v: 18, text: 'Indeed I have all and abound. I am full, having received from Epaphroditus the things sent from you, a sweet-smelling aroma, an acceptable sacrifice, well pleasing to God.' },
      { v: 19, text: 'And my God shall supply all your need according to His riches in glory by Christ Jesus.' },
      { v: 20, text: 'Now to our God and Father be glory forever and ever. Amen.' },
      { v: 21, text: 'Greet every saint in Christ Jesus. The brethren who are with me greet you.' },
      { v: 22, text: 'All the saints greet you, but especially those who are of Caesar\'s household.' },
      { v: 23, text: 'The grace of our Lord Jesus Christ be with you all. Amen.' },
    ],
  },
];

/** Get unique book names from the library */
export function getBooks(): string[] {
  return [...new Set(BIBLE_LIBRARY.map(p => p.book))];
}

/** Get all chapters available for a given book */
export function getChapters(book: string): number[] {
  return BIBLE_LIBRARY
    .filter(p => p.book === book)
    .map(p => p.chapterNum);
}

/** Look up a specific passage */
export function getPassage(book: string, chapterNum: number): BiblePassage | undefined {
  return BIBLE_LIBRARY.find(p => p.book === book && p.chapterNum === chapterNum);
}
